### ISSUE TITLE
Refactor UserRepository Test File

### ISSUE THREAD

**Issue by JCookDev** [Mrcolin99/fitlit#8]
Now that we've deleted our mock data file, we need to refactor the UserRepository test file.
Below is a screenshot of what happens when I run "npm test" command:

<img width="813" alt="Screen Shot 2022-09-01 at 3 40 41 PM" src="https://user-images.githubusercontent.com/100865025/187998626-6045d748-2c36-4612-aae3-c64290d2c6a6.png">

However, I found a quick workaround. I commented out the imported mock data file and now I get this after running npm test:

<img width="703" alt="Screen Shot 2022-09-01 at 3 43 03 PM" src="https://user-images.githubusercontent.com/100865025/187998966-1af4d237-e85e-4ff5-90e0-30db76272991.png">

Even though our userRepository class is working properly, our tests are failing because we were using the mock data to test our class. I suggest we refactor this test by adding a beforeEach() method in our describe block.

**Comment by danalchapman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor UserRepository Test File](https://trello.com/c/ZqfzuHhX/89-refactor-userrepository-test-file)

**Comment by danalchapman** [comment]
Colin's refactoring and inclusion of `beforeEach()` cleaned up the code beautifully and all of our tests are passing as intended! Go team!
